### ISSUE TITLE
Handling service messages

### ISSUE THREAD

**Issue by efaisal** [luckydonald/pytg#1]
Currently not handling service messages

**Comment by luckydonald** [comment]
The referenced issues are from the bitbucket bugtracker. Not Github here.

**Comment by luckydonald** [comment]
I'll take it from here. Thanks efaisal.

**Comment by luckydonald** [comment]
We just have to pull-request a update to the CLI to send us this stuff :smile:

**Comment by luckydonald** [comment]
I believe this is almost done, right?
