### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by mweissen** [luckydonald/pytg#10]
A nice package - I want to use ist, but: I have tried both examples
tg.start() gives

>>> tg.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pytg/__init__.py", line 30, in start
    proc = subprocess.Popen([self._tg, '-k', self._pub], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/local/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
>>>

What is wrong?
And - by the way - is there any description how to use this package?

**Comment by efaisal** [comment]
This packages requires a modified version of telegram client (described in README). Did you point self.tg to telegram binary?

**Comment by mweissen** [comment]
i think I have done everything as described step by step, but I will try it
again.

2015-01-26 9:54 GMT+01:00 E A Faisal <notifications@github.com>:

> This packages requires a modified version of telegram client (described in
> README). Did you point self.tg to telegram binary?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/efaisal/pytg/issues/10#issuecomment-71429928>.
>



-- 
Mit freundlichen Grüßen / With kind regards
Martin Weissenböck
Gregor-Mendel-Str. 37, 1190 Wien
Austria / European Union

**Comment by mweissen** [comment]
I have taken a new virtual server with Ubuntu 14.04 LTE
This is a detailled report:

wget https://github.com/efaisal/tg/archive/master.zip -O tg.zip

Ok, no problems.

tar xzf tg.zip && cd tg

I get:

gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now

I try:

unzip tg.zip

and I get a subdirectory tg-master.
cd tg dioes not work, but cd tg.

./configure

gives

configure: error: No libconfig found. Try --disable-libconfig

Now

./configure --disable-liblua

Same message:

configure: error: No libconfig found. Try --disable-libconfig

next:

./configure --disable-liblua --disable-libconfig

creates the Make-file.

make


gcc -g -O2  -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated
-fno-strict-aliasing -fno-omit-frame-pointer -ggdb -I. -I. -c main.c
-o main.o

main.c:33:31: fatal error: readline/readline.h: No such file or directory

 #include <readline/readline.h>

                               ^

compilation terminated.

make: *** [main.o] Error 1

Sorry, I have no idea what I have to do.

Any hints?

Regards, Martin











2015-01-26 19:38 GMT+01:00 Martin Weissenboeck <mweissen@gmail.com>:

> i think I have done everything as described step by step, but I will try
> it again.
>
> 2015-01-26 9:54 GMT+01:00 E A Faisal <notifications@github.com>:
>
>> This packages requires a modified version of telegram client (described
>> in README). Did you point self.tg to telegram binary?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/efaisal/pytg/issues/10#issuecomment-71429928>.
>>
>
>
>
> --
> Mit freundlichen Grüßen / With kind regards
> Martin Weissenböck
> Gregor-Mendel-Str. 37, 1190 Wien
> Austria / European Union
>
>


-- 
Mit freundlichen Grüßen / With kind regards
Martin Weissenböck
Gregor-Mendel-Str. 37, 1190 Wien
Austria / European Union

**Comment by efaisal** [comment]
Try to install libreadline-dev. I think that's where readline header is in
Ubuntu

**Comment by mweissen** [comment]
Thanks for your fast response.

apt-get install libreadline-dev worked.

Next error:

gcc -g -O2  -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated
-fno-strict-aliasing -fno-omit-frame-pointer -ggdb -I. -I. -c main.c -o
main.o
In file included from main.c:51:0:
mtproto-client.h:23:24: fatal error: openssl/bn.h: No such file or directory
 #include <openssl/bn.h>

I have tried
apt-get install openssl-dev

Sorry, I am not Linux expert.  :-)

2015-01-28 13:49 GMT+01:00 E A Faisal <notifications@github.com>:

**Comment by justingood** [comment]
In Ubuntu the correct package name should be ```libssl-dev```

If you like, you might want to refer to how my [bootstrap script](https://github.com/justingood/terribot/blob/master/bootstrap.sh) handles the configuration. Keep in mind that this works the older 12.04 version of Ubuntu, since I ran into some problems with the newer one. YMMV.

**Comment by mweissen** [comment]
Have not been at home for some days...
Now: the dump.py demo program works - great!

Next step: I want to call the pytg library from a web2py application (www.web2py.com). But now I get "You have not registered telegram client". Does pytg need root rights?

I have changed the rights of the whole path to "auth"  (/root/.telegram/auth) to 644, but the message remains. Shall I put the file "auth" into another directory and change the __init__.py?

**Comment by efaisal** [comment]
Did web2py run as the same user when you run dump.py? If not try to use the
same user. My suspicion is that the user running web2py can't find
registration/key file (usually located in ~/.telegram directory).

**Comment by mweissen** [comment]
web2py's user is www-data and it should not run as root.
In my tests dump.py runs as root. Does pytg need the root rights?

Yes - I think it's a matter of the rights.  The auth file has root:root as
owner and group and the right 600. Is it a security risk to move the
registration file to the web2py file structure and change the owner to
www-data?

2015-02-09 17:03 GMT+01:00 E A Faisal <notifications@github.com>:

> Did web2py run as the same user when you run dump.py? If not try to use the
> same user. My suspicion is that the user running web2py can't find
> registration/key file (usually located in ~/.telegram directory).
> On Feb 9, 2015 11:51 PM, "mweissen" <notifications@github.com> wrote:
>
> > Have not been at home for some days...
> > Now: the dump.py demo program works - great!
> >
> > Next step: I want to call the pytg library from a web2py application (
> > www.web2py.com). But now I get "You have not registered telegram
> client".
> > Does pytg need root rights?
> >
> > I have changed the rights of the whole path to "auth"
> > (/root/.telegram/auth) to 644, but the message remains. Shall I put the
> > file "auth" into another directory and change the *init*.py?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/efaisal/pytg/issues/10#issuecomment-73531889>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/efaisal/pytg/issues/10#issuecomment-73534190>.
>



-- 
Mit freundlichen Grüßen / With kind regards
Martin Weissenböck
Gregor-Mendel-Str. 37, 1190 Wien
Austria / European Union

**Comment by efaisal** [comment]
The reason you got the error is because the telegram client will try to
find a directory called .telegram in www-data home directory. This special
directory contains the registration information for telegram client.
Assuming the home directory for www-data is /var/www, you can copy
/root/.telegram directory to /var/www and change the ownership of that
directory to www-data, for example:
$ sudo cp -R /root/.telegram /var/www
$ sudo chown -R www-data:www-data /var/www/.telegram

**Comment by mweissen** [comment]
Yes, this was the very helpfully.

My next step: a small "application" (in web2py terminology) to read my
telegram contact list.
I have used your example as a template and I tried to build a very simple
program using the following lines.
The index function returns a dict, which is displayed on the screen.

myid is ok, but  tg.start() seems to have an endless loop - it never comes
back.

------------------------------------

import sys
import os
from datetime import datetime, timedelta
import pytg
from pytg.utils import coroutine, broadcast
from pytg.tg import (dialog_list, chat_info, message, user_status,
user_info, contact_list, service_message,)

def index():

    telegram = '/home/mweissen/hometelegram/tg/telegram'
    pubkey = '/home/mweissen/hometelegram/tg-server.pub'
    *home = '/home/www-data' *
*    os.environ['HOME']=home*  *# without I get **<class
'pytg.TelegramError'> Undefined 'HOME' environment variable*
    try:
        tg=pytg.Telegram(telegram, pubkey)
    except e:
        return dict(message=e)

    res = []  *# I want to collect the results in a list*
    myid=tg.whoami()


    @coroutine
    def dump_msg():
        try:
            while True:
                msg = (yield)
                res.append(msg)
        except GeneratorExit:
            pass

    d = dump_msg()

    # Create processing pipeline
    pipeline = broadcast([
        message(d),
        user_status(d),
        dialog_list(d),
        chat_info(d),
        user_info(d),
        contact_list(d),
        service_message(d),
    ])

    # Register our processing pipeline
    tg.register_pipeline(pipeline)

   *# myid is ok, but the following statement seems to be endless*
*   # more: after tg.start() I have to restart web2py*

    # Start telegram cli
    tg.start()

    tg.poll()
    if tg.ready():
        tg.contact_list()
    if tg.ready():
        tg.user_contact_list()

    tg.quit()
    return dict(message=res)

2015-02-10 6:12 GMT+01:00 E A Faisal <notifications@github.com>:

> The reason you got the error is because the telegram client will try to
> find a directory called .telegram in www-data home directory. This special
> directory contains the registration information for telegram client.
> Assuming the home directory for www-data is /var/www, you can copy
> /root/.telegram directory to /var/www and change the ownership of that
> directory to www-data, for example:
> $ sudo cp -R /root/.telegram /var/www
> $ sudo chown -R www-data:www-data /var/www/.telegram
>
>
> On Tue Feb 10 2015 at 12:12:29 AM mweissen <notifications@github.com>
> wrote:
>
> > web2py's user is www-data and it should not run as root.
> > In my tests dump.py runs as root. Does pytg need the root rights?
> >
> > Yes - I think it's a matter of the rights. The auth file has root:root as
> > owner and group and the right 600. Is it a security risk to move the
> > registration file to the web2py file structure and change the owner to
> > www-data?
> >
> > 2015-02-09 17:03 GMT+01:00 E A Faisal <notifications@github.com>:
> >
> > > Did web2py run as the same user when you run dump.py? If not try to use
> > the
> > > same user. My suspicion is that the user running web2py can't find
> > > registration/key file (usually located in ~/.telegram directory).

**Comment by mweissen** [comment]
May I ask again?

2015-02-10 10:49 GMT+01:00 Martin Weissenboeck <mweissen@gmail.com>:

> Yes, this was the very helpfully.
>
> My next step: a small "application" (in web2py terminology) to read my
> telegram contact list.
> I have used your example as a template and I tried to build a very simple
> program using the following lines.
> The index function returns a dict, which is displayed on the screen.
>
> myid is ok, but  tg.start() seems to have an endless loop - it never comes
> back.
>
> ------------------------------------
>
> import sys
> import os
> from datetime import datetime, timedelta
> import pytg
> from pytg.utils import coroutine, broadcast
> from pytg.tg import (dialog_list, chat_info, message, user_status,
> user_info, contact_list, service_message,)
>
> def index():
>
>     telegram = '/home/mweissen/hometelegram/tg/telegram'
>     pubkey = '/home/mweissen/hometelegram/tg-server.pub'
>     *home = '/home/www-data' *
> *    os.environ['HOME']=home*  *# without I get **<class
> 'pytg.TelegramError'> Undefined 'HOME' environment variable*
>     try:
>         tg=pytg.Telegram(telegram, pubkey)
>     except e:
>         return dict(message=e)
>
>     res = []  *# I want to collect the results in a list*
>     myid=tg.whoami()
>
>
>     @coroutine
>     def dump_msg():
>         try:
>             while True:
>                 msg = (yield)
>                 res.append(msg)
>         except GeneratorExit:
>             pass
>
>     d = dump_msg()
>
>     # Create processing pipeline
>     pipeline = broadcast([
>         message(d),
>         user_status(d),
>         dialog_list(d),
>         chat_info(d),
>         user_info(d),
>         contact_list(d),
>         service_message(d),
>     ])
>
>     # Register our processing pipeline
>     tg.register_pipeline(pipeline)
>
>    *# myid is ok, but the following statement seems to be endless*
> *   # more: after tg.start() I have to restart web2py*
>
>     # Start telegram cli
>     tg.start()
>
>     tg.poll()
>     if tg.ready():
>         tg.contact_list()
>     if tg.ready():
>         tg.user_contact_list()
>
>     tg.quit()
>     return dict(message=res)
>
> 2015-02-10 6:12 GMT+01:00 E A Faisal <notifications@github.com>:
>
>> The reason you got the error is because the telegram client will try to
>> find a directory called .telegram in www-data home directory. This special
>> directory contains the registration information for telegram client.
>> Assuming the home directory for www-data is /var/www, you can copy
>> /root/.telegram directory to /var/www and change the ownership of that
>> directory to www-data, for example:
>> $ sudo cp -R /root/.telegram /var/www
>> $ sudo chown -R www-data:www-data /var/www/.telegram
>>
>>
>> On Tue Feb 10 2015 at 12:12:29 AM mweissen <notifications@github.com>
>> wrote:
>>
>> > web2py's user is www-data and it should not run as root.
>> > In my tests dump.py runs as root. Does pytg need the root rights?
>> >
>> > Yes - I think it's a matter of the rights. The auth file has root:root
>> as
>> > owner and group and the right 600. Is it a security risk to move the
>> > registration file to the web2py file structure and change the owner to
>> > www-data?
>> >
>> > 2015-02-09 17:03 GMT+01:00 E A Faisal <notifications@github.com>:
>> >
>> > > Did web2py run as the same user when you run dump.py? If not try to
>> use
>> > the
>> > > same user. My suspicion is that the user running web2py can't find
>> > > registration/key file (usually located in ~/.telegram directory).

**Comment by efaisal** [comment]
It's difficult to say for certain. It could be that the telegram client
binary was not found. Check the installation guide from the README if
there's something missing and try the example again.

**Comment by luckydonald** [comment]
Please recheck if it works in the newest version.
More infos about the huge update today in the readme file.

**Comment by luckydonald** [comment]
If this is not solved, please reopen.
