### ISSUE TITLE
May need to update example command_who_am_i.py

### ISSUE THREAD

**Issue by Shatnerz** [luckydonald/pytg#100]
### The problem
in command_who_am_i.py

```python
res = s.get_self()
username = res.username  # this will raise a key error
print res.keys()

# [u'first_name',
#  u'print_name',
#  u'peer_type',
#  u'when',
#  u'phone',
#  u'last_name',
#  u'flags',
#  u'peer_id',
#  u'id']
```

I don't know the inner working of pytg and tg, but I suspect Telegram changed the response slightly and username is no longer used. It may be worth updating the examples. I may get around to a pull request with the changes.

### Your environment
OS: Ubuntu 14.04
Python: 2.7
pytg: 0.4.10

**Comment by luckydonald** [comment]
Does the account of you bot _has_ a @username?

**Comment by Shatnerz** [comment]
Oh okay. I was checking out a user, not a bot. They may have been the problem.

**Comment by luckydonald** [comment]
I assume this is resolved?

**Comment by Shatnerz** [comment]
Yes
