### ISSUE TITLE
Send Photo with text message

### ISSUE THREAD

**Issue by GiovanniCardamone** [luckydonald/pytg#103]
There is a way to send a Photo with message Attacched?

i cannot found on doc.

**Comment by luckydonald** [comment]
Yes, `send_photo` has a caption parameter.
[sender.py:49](https://github.com/luckydonald/pytg/blob/5d21b208480de130d34416c918546b560868d5d7/pytg/sender.py#L49)

**Comment by GiovanniCardamone** [comment]
wow thanks, ill close, very helpful.
