### ISSUE TITLE
Bot_ping sometimes reply all old message

### ISSUE THREAD

**Issue by Bertysoft70** [luckydonald/pytg#104]
### The problem
I modify bot_ping to reply some message.
If cli system stop for some reasone at startup the old message Will Be reply again

### Your environment
Version of python 2.7.9
pytg last versione 
Linux on raspberry

Thank you very much

**Comment by luckydonald** [comment]
Yes.

**Comment by luckydonald** [comment]
This is a problem with the CLI. 
There was a backlog feature preventing this, but it seems to be broken now.

**Comment by Bertysoft70** [comment]
Thank you very much for your support.  i like your program.
For now i add the following line in the bot_ping that i skip all message with date different of today.
maybe was help full for some other people.
if msg.sender.when.split()[0]==strftime("%Y-%m-%d"):
      print "today message"
else:
      print "old message"
      continue
in any case the all message arrive again from outside, like was not read the first time.

Thank you for your support.
