### ISSUE TITLE
telegram not running

### ISSUE THREAD

**Issue by CaptainPoddeldunkt** [luckydonald/pytg#11]
If I try one of the examples (dump.py / pingbot.py), I get this error message:
Traceback (most recent call last):
  File "pingbot.py", line 66, in <module>
    tg.poll()
  File "/usr/local/lib/python2.7/dist-packages/pytg/__init__.py", line 38, in poll
    raise TelegramError('telegram not running')
pytg.TelegramError: telegram not running

Telegram is installed and is working. What am I doing wrong?

**Comment by efaisal** [comment]
I suspect that telegram did not start. tg.start() is the method for
starting telegram via subprocess(). Unfortunately I didn't handle if
telegram failed to start e.g. missing pubkey in tg.start().

**Comment by luckydonald** [comment]
Please recheck if this works in the newest version.
More infos about the huge update today in the readme file.

**Comment by luckydonald** [comment]
If this happens again, please file a new bug.
