### ISSUE TITLE
Can use this to auto-forward message in a group to another chat or bot?

### ISSUE THREAD

**Issue by B44ST** [luckydonald/pytg#115]
### The problem
Describe your issue here.

### Your environment
Fill out your used versions:

Component | Version 
--------- | --------------
python    | `X.X.X`          
pytg      | `X.X.X`          
OS        | `Mac OS 10.9.5`  

### Steps to reproduce
Detailed steps to reproduce the issue.
```
insert any relevant code between the above and below backticks
```

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

**Comment by luckydonald** [comment]
Yes.
