### ISSUE TITLE
no event for message received in channel

### ISSUE THREAD

**Issue by 0xecute** [luckydonald/pytg#124]
### The problem
I don't receive messages from channel in the python script (dump.py as reference)

### Your environment
Fill out your used versions:

Component | Version 
--------- | --------------
python    | `2.7.13` 
pytg      | `0.4.10`      
OS        | `Last Ubuntu`

### Expected behaviour
I should receive an event with the message posted in the channel. 
I m no admin of the channel by the way.

### Actual behaviour
No event are received. Then when I run ./telegram-cli it shows me directly all messages received from the channel that are unread.

Thanks for this great library :)

**Comment by luckydonald** [comment]
Please specify which is the `Last Ubuntu` (`$ uname -a`), as that will change in the future.

Can you check if it works with the `--json` flag set?
Best to try starting the CLI with the same parameters as pytg does, they get printed in the [debug output](https://github.com/luckydonald/pytg#in-case-of-errors).

**Comment by bedoxonline** [comment]
Hello, did you manage to fix your issue? I have exactly the same error and lagging since several hours now...
Thanks

**Comment by 0xecute** [comment]
Hi.
I read somewhere that for big groups (like more than 500 people.. or more, don't remember exactly), the library doesn't work correctly.
I finally switch to https://github.com/vysheng/tg which has fixed this bug.
I finally used telethon because it was more adapted to my project. Sorry ^^
