### ISSUE TITLE
Telegram.stop_cli() function doesn't work

### ISSUE THREAD

**Issue by haghighi-ahmad** [luckydonald/pytg#129]
### The problem
I call `stop_cli()` function at the end of script, and every time following exception raised:
```python
Traceback (most recent call last):
  File "mytg.py", line 70, in <module>
    tg.stop_cli()
  File "/home/XXX/lib/python3.6/site-packages/pytg/__init__.py", line 129, in stop_cli
    self._proc.communicate('quit\n')  # report this error in the bugtracker!
  File "/usr/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1499, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/XXX/lib/python3.6/site-packages/pytg/__init__.py", line 129, in stop_cli
    self._proc.communicate('quit\n')  # report this error in the bugtracker!
  File "/usr/lib/python3.6/subprocess.py", line 818, in communicate
    raise ValueError("Cannot send input after starting communication")
ValueError: Cannot send input after starting communication
read: Connection reset by peer
```

### Environment

Component | Version 
--------- | --------------
python    | `3.6.3`          
pytg      | `0.4.10`         
OS        | `Ubuntu 17.10` 

### Steps to reproduce
```python
from pytg import Telegram
tg = Telegram(....)
# my code
tg.stop_cli()
```

**Comment by luckydonald** [comment]
The first exception seem to indeed be a bug: `TypeError: memoryview: a bytes-like object is required, not 'str'`.
The second exception, `ValueError: Cannot send input after starting communication` might be due to the CLI already being terminated?

**Comment by haghighi-ahmad** [comment]
@luckydonald  

> might be due to the CLI already being terminated?

No, it's not.   
After the above exception, CLI is running  and works fine (respond to requests).

**Comment by tomp** [comment]
I believe the exception is raised because pytg is passing a string argument to self._proc.communicate(), rather than a bytes object, in pytg/__init__.py, line 142, 
`            # has not terminated yet.
            self._proc.communicate('quit\n')  # report this error in the bugtracker!`
In python2, that argument is a string, but in python3 it needs to be a bytes object, unless the subprocess was spawned with `universal_newlines=True`.  Setting `universal_newlines=True` when the subprocess is created sounds like it would fix the problem for python3 without breaking things for python2.

**Comment by luckydonald** [comment]
@tomp 

So probably 
```python
from luckydonaldUtils.encoding import to_binary as b
self._proc.communicate(b('quit\n'))
```
should be enough?

Could you check that in python 3?

**Comment by luckydonald** [comment]
The 
```py
 # report this error in the bugtracker!
``` 
is very cute, I like it :D

**Comment by tomp61** [comment]
@luckydonald  
```
from luckydonaldUtils.encoding import to_binary as b
self._proc.communicate(b('quit\n'))
```
seems to work fine in python 3.

**Comment by Orgilus** [comment]
No. It doesnʼt work in Python 3:

Traceback (most recent call last):
  File "/home/pi/Scripts/teletest", line 15, in <module>
    self._proc.communicate(to_binary("quit\n"))
NameError: name 'self' is not defined
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 801, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1431, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
read: Connection reset by peer

**Comment by luckydonald** [comment]
Your error is different though.
```py
self._proc.communicate(to_binary("quit\n"))
NameError: name 'self' is not defined
```
Check that `self` exists. If you want more help, attach your script here.

**Comment by luckydonald** [comment]
Actually this has to be fixed in the file mentioned.

**Comment by luckydonald** [comment]
Please test by [installing from source](https://github.com/luckydonald/pytg#install-from-source) if that solved it.

**Comment by Orgilus** [comment]
Now it seems to be another error:

Traceback (most recent call last):
  File "/home/pi/Scripts/teletest", line 6, in <module>
    abschicken ("Werner_Hintze", nachricht)
  File "/home/pi/Scripts/sendeTelegram.py", line 16, in sendeAnTelegram
    sender.safe_quit()
  File "/home/pi/.local/lib/python3.5/site-packages/pytg/sender.py", line 630, in command_alias
    return self.execute_function(command_name, *args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/pytg/sender.py", line 320, in execute_function
    result = self._do_send(request, answer_timeout=self.default_answer_timeout, retry_connect=retry_connect)
  File "/home/pi/.local/lib/python3.5/site-packages/pytg/sender.py", line 507, in _do_send
    raise ConnectionError("Remote end closed")
pytg.exceptions.ConnectionError: Remote end closed

**Comment by Orgilus** [comment]
I can avoid it so:

    try:
        sender.safe_quit()
    except:
        pass

Bt I donʼt like this.

**Comment by luckydonald** [comment]
You should do 
```py
try:
    sender.safe_quit()
except ConnectionError:
    print('CLI already stopped')
```
