### ISSUE TITLE
Any example of uploading image?

### ISSUE THREAD

**Issue by avinassh** [luckydonald/pytg#13]
I want to upload image from my local computer (where bot is running) to telegram. how do I do it? any example?

**Comment by avinassh** [comment]
okay, after looking at source, I figured. just need to call `send_photo` on Telegram object. Something like this:

    tg.send_photo(peer, '/path/to/image')

**Comment by luckydonald** [comment]
This needs indeed Documentation.
Now (#19) more then ever.

**Comment by luckydonald** [comment]
Since my documentation sucks anyway, I gonna close this. Yolo.

**Comment by avinassh** [comment]
ha ha
