### ISSUE TITLE
How to keep a CLI already running in json mode on port 4458 ?

### ISSUE THREAD

**Issue by sahPraveen** [luckydonald/pytg#136]
I have installed the pytg using pip and running below code for sending message.
Not sure what is to be kept running on localhost for this program to work!

### Steps to reproduce
Detailed steps to reproduce the issue.

```py
from pytg.sender import Sender
sender = Sender(host="127.0.0.1", port=4458)
res = sender.msg("sahpraveen", "delivered!")
print("Response: {response}".format(response=res))

```

### Expected behaviour
Message to be sent on Telegram app

### Actual behaviour
```bash
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\pytg\sender.py", line 475, in _do_send
    self.s.connect((self.host, self.port_out))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

Component | Version 
--------- | --------------
python    | Python 3.6.6      
pytg      | pytg-0.4.10    
OS        | Win10 x64bit

**Comment by luckydonald** [comment]
How did you start `telegram-cli`?

**Comment by sahPraveen** [comment]
I was not using telegram-cli.
Moved to another approach.
Thanks
