### ISSUE TITLE
How do I install this with pip and run within virtualenv?

### ISSUE THREAD

**Issue by avinassh** [luckydonald/pytg#14]
well, I activated virtualenv and installed with following commands: 

    $ git clone https://github.com/efaisal/pytg.git && cd pytg && python setup.py install

but when I run pingbot file, I am getting following error:

	(venv)avis-MacBook-Pro:tg avi$ python pytg/pingbot.py
	Traceback (most recent call last):
	  File "pytg/pingbot.py", line 11, in <module>
	    import pytg
	  File "/Users/avi/Documents/telegram-bot/tg/pytg/pytg/__init__.py", line 7, in <module>
	    from utils import start_pipeline
	ImportError: No module named 'utils'

I also tried installing like this, but I am still getting same error:

    pip install git+https://github.com/efaisal/pytg.git

**Comment by avinassh** [comment]
okay, I was getting this error, because I was running under Python 3, I did not know it is Python 2 only. (or may be not, but atleast it works fine with Python 2 in virtualenv)

**Comment by efaisal** [comment]
You're right. At the moment, it only support python 2. Unfortunately my
hand is tied with my day job to add python 3 support. I would appreciate if
anybody can work on supporting python 3.

**Comment by luckydonald** [comment]
Since the Huge update today it should work with python 3.

**Comment by luckydonald** [comment]
Closing this. If you got problems, open a new issue please.
