### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by joihn** [luckydonald/pytg#15]
hello

I have an error when execute "make"

here's the output
gcc -g -O2 -I/usr/include/lua5.2  -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -I. -I. -c main.c -o main.o
gcc -g -O2 -I/usr/include/lua5.2  -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -I. -I. -c loop.c -o loop.o
gcc -g -O2 -I/usr/include/lua5.2  -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -I. -I. -c interface.c -o interface.o
interface.c: In function ‘set_interface_callbacks’:
interface.c:1568:3: error: ‘CPPFunction’ is deprecated [-Werror=deprecated-declarations]
   rl_attempted_completion_function = (CPPFunction *) complete_text;
   ^
cc1: all warnings being treated as errors
Makefile:30: recipe for target 'interface.o' failed
make: *** [interface.o] Error 1

**Comment by luckydonald** [comment]
Hold on for the merge wit pytg2.
This will need no custom CLI no more.

**Comment by luckydonald** [comment]
Now is merged. Follow the Instructions in the Readme. If something is unclear, please shout at me, so I can improve the instructions.

**Comment by luckydonald** [comment]
Please Reopen if not resolved by the update..
