### ISSUE TITLE
changes in last version of Telegram Cli

### ISSUE THREAD

**Issue by zeandrade** [luckydonald/pytg#16]
last version of Telegram Cli rename settings path, that must be fixed in pytg
in \_\_init\_\_.py , line 120
```python
#was 
authfile = os.path.join(os.environ['HOME'], '.telegram', 'auth')
#now:
authfile = os.path.join(os.environ['HOME'], '.telegram-cli', 'auth')
```

**Comment by luckydonald** [comment]
This will be fixed with the merge of the pytg2 fork, soon.
(Actually that particular function will not exist any longer, sorry. If you still need that functionallity, drop a note.)

**Comment by luckydonald** [comment]
BAM. there you go.

**Comment by zeandrade** [comment]
Thanks @luckydonald
