### ISSUE TITLE
Huge Update, Version 0.4.1

### ISSUE THREAD

**Issue by luckydonald** [luckydonald/pytg#19]
Good news:
Pytg is up to date!
I took maintainance of this Project and merged my fork pytg2 into this.
There is a **How to Update** section in the readme.
If there are any questions left uncovered, ask away.    
Thanks!

**Comment by luckydonald** [comment]
Good news:
Pytg is up to date!
I took maintainance of this Project and merged my fork pytg2 into this.
#13 #14 #15 #16 #8

**Comment by justingood** [comment]
:+1: 
Very pleased this project is coming back to life. Thanks @luckydonald !

**Comment by zeandrade** [comment]
@luckydonald Look this:
```python
tg = Telegram( telegram='/path/tg/bin/telegram-cli', pubkey_file='/path/tg-server.pub')
/path/tg/bin/telegram-cli: invalid option -- '-'
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pytg/__init__.py", line 48, in __init__
    raise AssertionError("CLI Process died.")
AssertionError: CLI Process died.
```

**Comment by zeandrade** [comment]
Ooops, sorry @luckydonald ,my mistake : I used 1.2.0 version of tg ( whithout --json support) , I updated to 1.3.1 and works fine!
