### ISSUE TITLE
[Windows] ImportError: No module named 'DictObject'

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [luckydonald/pytg#20]
I get an ImportError out of \pytg\pytg\pytg\sender.py

ImportError: No module named 'DictObject'

**Comment by luckydonald** [comment]
Should automatically get installed already by ```python setup.py install```.
The dependency can be installed manually with 
```shell
pip install DictObject
```

**Comment by Karlheinzniebuhr** [comment]
running install
running bdist_egg
running egg_info
creating pytg.egg-info
writing requirements to pytg.egg-info\requires.txt
writing pytg.egg-info\PKG-INFO
writing top-level names to pytg.egg-info\top_level.txt
writing dependency_links to pytg.egg-info\dependency_links.txt
writing manifest file 'pytg.egg-info\SOURCES.txt'
reading manifest file 'pytg.egg-info\SOURCES.txt'
writing manifest file 'pytg.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\pytg
copying pytg\argument_types.py -> build\lib\pytg
copying pytg\encoding.py -> build\lib\pytg
copying pytg\exceptions.py -> build\lib\pytg
copying pytg\fix_msg_array.py -> build\lib\pytg
copying pytg\fix_plain_output.py -> build\lib\pytg
copying pytg\receiver.py -> build\lib\pytg
copying pytg\result_parser.py -> build\lib\pytg
copying pytg\sender.py -> build\lib\pytg
copying pytg\test.py -> build\lib\pytg
copying pytg\utils.py -> build\lib\pytg
copying pytg\__init__.py -> build\lib\pytg
creating build\bdist.win32
creating build\bdist.win32\egg
creating build\bdist.win32\egg\pytg
copying build\lib\pytg\argument_types.py -> build\bdist.win32\egg\pytg
copying build\lib\pytg\encoding.py -> build\bdist.win32\egg\pytg
copying build\lib\pytg\exceptions.py -> build\bdist.win32\egg\pytg
copying build\lib\pytg\fix_msg_array.py -> build\bdist.win32\egg\pytg
copying build\lib\pytg\fix_plain_output.py -> build\bdist.win32\egg\pytg
copying build\lib\pytg\receiver.py -> build\bdist.win32\egg\pytg
copying build\lib\pytg\result_parser.py -> build\bdist.win32\egg\pytg
copying build\lib\pytg\sender.py -> build\bdist.win32\egg\pytg
copying build\lib\pytg\test.py -> build\bdist.win32\egg\pytg
copying build\lib\pytg\utils.py -> build\bdist.win32\egg\pytg
copying build\lib\pytg\__init__.py -> build\bdist.win32\egg\pytg
byte-compiling build\bdist.win32\egg\pytg\argument_types.py to argument_types.pyc
byte-compiling build\bdist.win32\egg\pytg\encoding.py to encoding.pyc
byte-compiling build\bdist.win32\egg\pytg\exceptions.py to exceptions.pyc
byte-compiling build\bdist.win32\egg\pytg\fix_msg_array.py to fix_msg_array.pyc
byte-compiling build\bdist.win32\egg\pytg\fix_plain_output.py to fix_plain_output.pyc
byte-compiling build\bdist.win32\egg\pytg\receiver.py to receiver.pyc
byte-compiling build\bdist.win32\egg\pytg\result_parser.py to result_parser.pyc
byte-compiling build\bdist.win32\egg\pytg\sender.py to sender.pyc
byte-compiling build\bdist.win32\egg\pytg\test.py to test.pyc
byte-compiling build\bdist.win32\egg\pytg\utils.py to utils.pyc
byte-compiling build\bdist.win32\egg\pytg\__init__.py to __init__.pyc
creating build\bdist.win32\egg\EGG-INFO
copying pytg.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying pytg.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying pytg.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying pytg.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying pytg.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\pytg-0.4.1-py2.7.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing pytg-0.4.1-py2.7.egg
Removing c:\python27\lib\site-packages\pytg-0.4.1-py2.7.egg
Copying pytg-0.4.1-py2.7.egg to c:\python27\lib\site-packages
pytg 0.4.1 is already the active version in easy-install.pth

Installed c:\python27\lib\site-packages\pytg-0.4.1-py2.7.egg
Processing dependencies for pytg==0.4.1
Searching for dictobject==0.1.1
Best match: dictobject 0.1.1
Processing dictobject-0.1.1-py2.7.egg
dictobject 0.1.1 is already the active version in easy-install.pth

Using c:\python27\lib\site-packages\dictobject-0.1.1-py2.7.egg
Finished processing dependencies for pytg==0.4.1



I'm still getting this error:
Traceback (most recent call last):
  File "Telegram_spam.py", line 9, in <module>
    from pytg.sender import Sender
  File "C:\Users\Karl\Desktop\pytg\pytg\pytg\sender.py", line 19, in <module>
    from DictObject import DictObject
ImportError: No module named 'DictObject'

**Comment by luckydonald** [comment]
oh. I guess that might be an issue with Windows having case insensitive paths. (how retro)
can you try in a python shell
```python
from dictobject import DictObject
```
please?

**Comment by Karlheinzniebuhr** [comment]
lol yes I get import error on that lowercase import, this works but only on python 2.7 I have several version installed perhaps that's my problem I'll check 
from DictObject import DictObject

**Comment by luckydonald** [comment]
Any updates?

**Comment by luckydonald** [comment]
Did you solve it?

**Comment by luckydonald** [comment]
I closed it, as there was no answer.
