### ISSUE TITLE
Can't make a working bot

### ISSUE THREAD

**Issue by JuanPotato** [luckydonald/pytg#22]
I cannot make a simple code to just send a message to someone. Can you provide us with a fully working example that will atleast send and receive one message?

**Comment by justingood** [comment]
Check out the [ping](https://github.com/luckydonald/pytg/blob/master/examples/ping.py) example script. It's a well documented example of bot-like interaction.

**Comment by JuanPotato** [comment]
@justingood I'm sorry if I am a noob, but how do I get it to work? I run it it using python ping.py but then I just get nothing. Should I be editing anything inside the file? (yes I read it)

**Comment by luckydonald** [comment]
The ping example needs a altedy running cli somewhere.
The readme shows a way to start the cli from python.
I am on vaccation for a week without internet access, so I will noz be able to support you, sorry.

**Comment by luckydonald** [comment]
*Already

**Comment by JuanPotato** [comment]
@luckydonald :| tried that, `bind: address already in use` well time to go back to lua

**Comment by luckydonald** [comment]
This just means, you are already having a cli listening at that port.
(Or you had. It can take up to 2 minutes to release the port) or, just use an other port. Specify it as ```port=``` in the Telegram constructor.
