### ISSUE TITLE
coroutine decorator is missing call to @wraps

### ISSUE THREAD

**Issue by caumons** [luckydonald/pytg#23]
Thanks for this really useful lib! Here is my little contribution:

`coroutine()` decorator at `utils.py` module is missing [wraps decorator](https://docs.python.org/2/library/functools.html#functools.wraps). Reference [here](http://stackoverflow.com/questions/308999/what-does-functools-wraps-do).

Proposed fix (using python 2.7):

```
from functools import wraps


def coroutine(func):
    """
    Skips to the first yield when the generator is created.
    Used as decorator, @coroutine
    :param func: function (generator) with yield.
    :return: generator
    """

    @wraps(func)  # <== Added @wraps here
    def start(*args, **kwargs):
        try:
            cr = func(*args, **kwargs)
            try:
                next(cr)
            except NameError:  # not defined, python 2
                cr.next()
            return cr
        except StopIteration:
            return
        except KeyboardInterrupt:
            raise StopIteration

    return start
```

**Comment by luckydonald** [comment]
Without the ability to test code on my vacations, I am not quite sure what happens there...
The coroutine docstring will replace the functions docstring where the decorator is applied to?

Anyway, feel free to submit a pull request yourself.

**Comment by luckydonald** [comment]
I believe I rewrote that code part, and lost the overview of what was the issue here.
If this is still is an issue, reopen this issue please.
