### ISSUE TITLE
Send messages to people by there usernames

### ISSUE THREAD

**Issue by Software-Design** [luckydonald/pytg#24]
I want to send messages to users by their usernames (without knowing their phone number). In the CLI i can do "contact_search @username" and the output contains the the real name which I can use to message the person directly.

I can't find out how this can be implemented with this wrapper. How can I archived that?

**Comment by Software-Design** [comment]
That worked for me for the moment:

    from pytg import Telegram
    import json
    tg = Telegram(
		telegram="/var/lib/tg/bin/telegram-cli",
		pubkey_file="/var/lib/tg/server.pub")
    sender = tg.sender
    json = json.loads(sender.raw('contact_search @username'))
    sender.send_msg(json[0]['print_name'],u'Test')

**Comment by luckydonald** [comment]
i believe the missing function is already in the beta branch, have a look there too.
But until it gets merged, the ```raw```  function is the way to go.

**Comment by luckydonald** [comment]
I'll work on this the week.

**Comment by luckydonald** [comment]
I believe I merged that by now.

**Comment by luckydonald** [comment]
You should be able to use ```contact_search("username")``` now

**Comment by faralin** [comment]
i can't search people by their usernames whom are not in my contact by number.what should i do?

**Comment by luckydonald** [comment]
Have you tried that command in the cli?
also you did you try ```@username``` as well?

**Comment by luckydonald** [comment]
With #51 beeing fixed, that indicates it should be working now.
