### ISSUE TITLE
I didnot receive message

### ISSUE THREAD

**Issue by huyhoang1990** [luckydonald/pytg#25]
I installed and sent message successfully, but i cannot create a program for receiving messsage from other user . i did as same file https://github.com/luckydonald/pytg/blob/master/examples/dump.py but nothing happend

This is my code

```python
from pytg.utils import coroutine
@coroutine # from pytg.utils import coroutine
def main_loop():
    while True:
        msg = (yield) # it waits until it got a message, stored now in msg.
        print("Message: ", msg.text)

from pytg import Telegram
tg = Telegram(
        telegram="/home/vagrant/telegram/tg/bin/telegram-cli",
        pubkey_file="/home/vagrant/telegram/tg/tg-server.pub")

receiver = tg.receiver
receiver.start()
receiver.message(main_loop())
```

And i used other accout to send to this account. but the message did display on console.
Thanks

**Comment by luckydonald** [comment]
Hmm, If you could see It on console you probably the cli pytg used was not the same as you had in the console. 
Also, if everything works how it should, you should not get messages in the cli.

**Comment by luckydonald** [comment]
Lacking any updates here I'll close this issue. Feel free to reopen if you still need help.
