### ISSUE TITLE
Cannot use sender

### ISSUE THREAD

**Issue by Meisolsson** [luckydonald/pytg#26]
When sender is imported i crash with the error 

```
File "build/bdist.macosx-10.6-intel/egg/pytg/__init__.py", line 22, in __init__
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytg-0.4.1-py2.7.egg/pytg/sender.py", line 204
    def execute_function(self, function_name, *arguments, reply_id=None, enable_preview=None, **kwargs):
                                                                 ^
SyntaxError: invalid syntax
```

**Comment by luckydonald** [comment]
Please give me information about your platform, as well as the used python version.

**Comment by Meisolsson** [comment]
I'm on OSX 10.10.3 with Python version 2.7.9.
I downloaded the 0.4.1 from your repo and that works, but not the current master branch
On Jun 8, 2015 9:21 AM, Luckydonald <notifications@github.com> wrote:Please give me information about your platform, as well as the used python version.

**Comment by luckydonald** [comment]
Okey, the error is found, the syntax in python 2 is a a bit more strict with ```*args``` and ```**kwargs``` http://stackoverflow.com/a/9873280
Testing python 3 compatibility and will push that soon.

**Comment by luckydonald** [comment]
should work now. please test.
