### ISSUE TITLE
error in send message

### ISSUE THREAD

**Issue by nim4n** [luckydonald/pytg#34]
Hi
I try to use this library but I get this error:

> sender.send_msg("some_user", u"nima")
> {u'error': u'can not parse arg #1', u'error_code': 38, u'result': u'FAIL'}

I'm using python2.7 and my code is:
> tg = Telegram(
>    telegram="bin/telegram-cli",
>    pubkey_file="tg-server.pub")
> sender = tg.sender

am I missed some thing?

**Comment by luckydonald** [comment]
Be sure that the user is already known by the cli, eg. Perform ```sender.dialog_list()``` before.
I would recommand using "user#1234" (or "chat#5678" for group chats) instead.
