### ISSUE TITLE
Starting pytg with nginx

### ISSUE THREAD

**Issue by egorvas** [luckydonald/pytg#35]
Hi, Im creating web server which sending telegram messages with pytg.
Server hosted on the DigitalOcean hosting.
When a starting server manually (this is flask server) everything works good, but when I start my server with nginx and uwsgi Ive got this error:

```python
open[config_file]: No such file or directory
Traceback (most recent call last):
  File "/opt/rest/app.py", line 34, in <module>
    from resource.Telegram import TelegramAdd
  File "/opt/rest/resource/Telegram.py", line 4, in <module>
    import senders.telegram
  File "/opt/rest/senders/telegram.py", line 11, in <module>
    pubkey_file="/opt/tg/rsa.pub")
  File "build/bdist.linux-x86_64/egg/pytg/__init__.py", line 49, in __init__
```

So, Im already make sure that way is correct and that www-data have permissions to this file.

Maybe have an idea how I canto fix it? Thankyou in advance!

**Comment by luckydonald** [comment]
To both the .pub and the cli executable?

**Comment by luckydonald** [comment]
Lacking an update I assume this as fixed or something. Feel free to reopen.
