### ISSUE TITLE
How to bulk import contacts

### ISSUE THREAD

**Issue by roshanavand** [luckydonald/pytg#41]
I'm trying to add thousands of contacts to my list.
Contacts are saved in a csv formatted file:
`Number, First name, Last name`
Right now I'm trying to add them one by one in a loop.
Is there any build in feature or can you suggest a better way of doing that?

**Comment by luckydonald** [comment]
You probably are asking for a way to import them into python/pytg automatically?
 
I'll not do the code for you, just in case you might do that for spammy purposes.
But I'll still can give you a direction to go.

You'll need to read the csv file, maybe with a csv parser like [https://docs.python.org/3/library/csv.html](https://docs.python.org/3/library/csv.html) - [(featured on google search)](http://lmgtfy.com/?q=python+csv)
And to add them, you want to use ```pytg```'s [```contact_add(phone, first_name, last_name)``` function](https://github.com/luckydonald/pytg/blob/master/DOCUMENTATION.md#contact-related)    
For how to setup ```pytg```, [the readme](https://github.com/luckydonald/pytg/blob/master/README.md) should hopefully be clear enough.

If you can provide me a good enough excuse, that it is not for spamming other users, or you have a detailed question, I'll happy to help you further :smiley:

**Comment by roshanavand** [comment]
Thank you for your reply,
I tried the same way as you explained here before, when I try to read contacts from a csv file and them one by one I run into this [issue](https://github.com/luckydonald/pytg/issues/40).
So I thought that could be better if there was a feature to add them all together, for example if could pass more than one argument to the `contact_add` function.

This is not in any ways connected to spamming,
Thanks again for your response.

**Comment by luckydonald** [comment]
There is no function to add more than one at a time, simply limited by how the cli did define the underlying command.
I missed that other issue, sorry. I'll look into that.
