### ISSUE TITLE
No pytg module found

### ISSUE THREAD

**Issue by mariusl** [luckydonald/pytg#45]
Hi
I have installed and compiled the code several times but still cannot import pytg. I get an error that there is no such module.
I am running on a rpi with a virtual environment using Python 2.7.3. I have tg installed and I can send message from the console with the Telegram-cli.

Any suggestions where to look please?

**Comment by mariusl** [comment]
It looks like the setup does not place the module in the python -dist-packages directory at all.

**Comment by mariusl** [comment]
This needed to run easy_install on the egg after the setup.py script has run.

**Comment by luckydonald** [comment]
You did ```python setup.py install```, right?

**Comment by mariusl** [comment]
Yes I did but it only worked after I ran the easy_install manually. I also changed the setup file a bit. I removed all Python 3.x directives and I added an explicit reference to Python 2.7 after the OS definitions. The Programming language directives seem to be duplicated but I cannot tell for sure if that is a problem as I am not to familiar with the Python environment.

**Comment by luckydonald** [comment]
Without an install log or something similar, I can't have a look into that.
