### ISSUE TITLE
pytg.exceptions.NoResponse

### ISSUE THREAD

**Issue by drr3d** [luckydonald/pytg#56]
Hi there..

first, i really enjoy and appreciate your work, 

i've found some issues like i attached the image below bro

![dsc_0164](https://cloud.githubusercontent.com/assets/6335497/11607932/80e4c588-9b8d-11e5-85aa-054af49eed84.jpg)

i don't know whats wrong, my connection seem good..

may be i miss something?

thx

**Comment by luckydonald** [comment]
This means the CLI didn't send any response. How did you start the CLI, manually or with python?
If started manually, did you start it with the ```--json``` flag?

**Comment by luckydonald** [comment]
added to documentation in commit 22e5b4ba91445cc88f924b142301880d97b2d069

**Comment by drr3d** [comment]
Hi donald,

yes i start the CLI manually with
```
./telegram-cli -P 6090 -W --json
```

and i start to learn how to use this package with ping.py, i think the problem was the:

```
sender.status_online()
```

so your solutions to add some err handling with:
```
try:
    sender.status_online(result_timeout=5)  # wait up to 5 seconds
except NoResponse:  # from pytg.exceptions import NoResponse
    print("CLI did not responded in time")
```

its work like a charm

Thx bro

**Comment by luckydonald** [comment]
Your welcome.

**Comment by luckydonald** [comment]
Honestly I have no Idea why that line fails so often :D
