### ISSUE TITLE
How to use resolve_username

### ISSUE THREAD

**Issue by masious** [luckydonald/pytg#68]
Hi.
I want to get the info of a channel and I need to call resolve_username method.
Here is how I use it:
```python
sender.resolve_username(username, retry_connect=retry_times)
a = sender.channel_info(username, retry_connect=retry_times)
return a
```

And here is the error I get:
```python
File "/home/masoud/.virtualenvs/pycho/local/lib/python2.7/site-packages/pytg/sender.py", line 341, in execute_function
    return result_parser(message)
TypeError: object() takes no parameters
```
I guess there might be something wrong with the way I use the function, but I don't know what that is...

**Comment by luckydonald** [comment]
Huh.

**Comment by luckydonald** [comment]
Related discussion: https://github.com/luckydonald/pytg/pull/47#issuecomment-189220181

**Comment by luckydonald** [comment]
Resolve username is used without `@` symbol. Also found the bug.

**Comment by luckydonald** [comment]
Related midway:
https://github.com/vysheng/tg/issues/1023

**Comment by luckydonald** [comment]
```python
import logging
logging.basicConfig(level=logging.DEBUG)
from pytg.sender import Sender
s = Sender("localhost", 4458)
foo = s.resolve_username("xkcdchannel")
```
```python
print(foo)
{'flags': 65665, 'print_name': 'xkcd', 'id': '$05000000ad8b183ceafc88ecfe525ebe', 'title': 'xkcd', 'admins_count': 0, 'participants_count': 0, 'peer_type': 'channel', 'kicked_count': 0, 'peer_id': 1008241581}
```

**Comment by masious** [comment]
@luckydonald The problem was with the version of my python. I was using python 2.7, which __call__() methods can not be called. In order to use `resolve_username` method, you "must" use python>=3.0.
Please mention that in the README file...
And thanks a lot for your help...

**Comment by luckydonald** [comment]
Huh. I'll investigate

**Comment by luckydonald** [comment]
I tested it with python 2.7, and it should in fact work.
```python
>>> from pytg.result_parser import OnlineEvent
>>> from DictObject import DictObject
>>> fake_event = DictObject(when="sometime", user={"user":"me", "type":"fake", "peer_id":"4458"})
>>> OnlineEvent()(fake_event)
{'when': 'sometime', 'user': {'cmd': u'fake#4458', 'peer_id': '4458', 'type': 'fake', 'user': 'me', 'name': ''}}
```
I **did** fix the error it in the meantime, so you probably installed [the fixed version](https://github.com/luckydonald/pytg/blob/master/CHANGELOG.md#version-048) when reinstalling pytg for python 3.

**Comment by masious** [comment]
Hi again. It seems that there are limits for resolving usernames, because I wasn't able to resolve any username yesterday. The server just didn't responded. Does anyone know these limits?!

**Comment by luckydonald** [comment]
Huh. Thats strange and undocumented.
