### ISSUE TITLE
send_file send png files as photo

### ISSUE THREAD

**Issue by a3dho3yn** [luckydonald/pytg#69]
### The problem
When passing a png file path to send_file method, it sends the file as photo (instead of uncompressed file)

### Your environment
Python3.4.3 on Manjaro

### Steps to reproduce
Run telegram-cli ```bin/telegram-cli -k tg-server.pub --json -P 9102 -W --accept-any-tcp```
```
from os import path
from pytg.sender import Sender
s = Sender('localhost', 9102)
s.send_file(u'Hossein_Taleghani', path.abspath('assets/sign.png'))
```

### Expected behaviour
Send file as uncompressed file.
send_document does what I expected

### Actual behaviour
Sends file as photo

**Comment by luckydonald** [comment]
`send_file` automatically detects the type as intended. What you are looking for is `send_document`

**Comment by luckydonald** [comment]
[Now](https://github.com/luckydonald/pytg/blob/826306a4ebaba094c95001ab374aad62d1fdb4a0/DOCUMENTATION.md) documented in the [DOCUMENTATION.md](https://github.com/luckydonald/pytg/blob/master/DOCUMENTATION.md)

**Comment by luckydonald** [comment]
Actually it isn't
