### ISSUE TITLE
Return message ID of sent message

### ISSUE THREAD

**Issue by kobybm** [luckydonald/pytg#80]
Hi and thank you for this project! 
 
I want to use the forward message (I've sent a document of 1 mega) but I don't know how can I get the message ID of the message I've sent.

**Comment by luckydonald** [comment]
This is indeed tricky, and I found no relaiable solution to this. The cli doesn't return anything except a "SUCCESS".
This is a limitation of the cli.

However you will *receive* your send messages too, so you could check the following messages if they are posted by the bot (`msg.own==True`), and at least make guesses.

**Comment by luckydonald** [comment]
I think the old issue https://github.com/vysheng/tg/issues/773 is related.

**Comment by luckydonald** [comment]
And as far as I know, the cli sends the messages async, so that is not an easy fix there too.

**Comment by Nanoseb** [comment]
To "bypass" this you can use the ```history``` function with only one message just after sending it the id will be there, it is not very clean but would probably work fine.

**Comment by luckydonald** [comment]
This is possible too.

**Comment by kobybm** [comment]
Hi @Nanoseb and @luckydonald - Thanks for the workaround! works perfectly!
